'use client';

import { CalculationResult } from '@/types';
import { Button } from '@/components/ui/button';
import { FileDown } from 'lucide-react';
import { ROOM_TYPES } from '@/lib/roomTypes';
import { useCurrency } from '@/context/CurrencyProvider';

type PDFExportProps = {
  result: CalculationResult;
  roomType: string;
  customRoomName?: string;
};

export function PDFExport({ result, roomType, customRoomName }: PDFExportProps) {
  const { market, format } = useCurrency();
  const handleExport = () => {
    const roomName = customRoomName || ROOM_TYPES[roomType]?.name || 'Room';
    const date = new Date().toLocaleDateString();

    // Create text content for the PDF
    const content = `
═══════════════════════════════════════════════════════════
  PEN LIGHTING CALCULATOR REPORT
  ${roomName} - ${result.area.toFixed(1)} ${result.areaUnit}
  Generated: ${date}
═══════════════════════════════════════════════════════════

ROOM DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Room Type: ${roomName}
  Area: ${result.area.toFixed(1)} ${result.areaUnit}

LIGHTING REQUIREMENTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Total Lumens Needed: ${result.totalLumensNeeded.toLocaleString()} lumens
  Lumens per Square Foot: ${result.lumensPerSqFt} lumens/ft²${
    result.ceilingFactor != null && result.ceilingFactor !== 1
      ? `
  Ceiling Height: ${result.ceilingHeightFt.toFixed(1)} ft (${result.ceilingFactor > 1 ? '+' : ''}${Math.round((result.ceilingFactor - 1) * 100)}% adjustment applied)`
      : ''
  }

FIXTURE SPECIFICATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Number of Fixtures: ${result.numberOfFixtures}
  Fixture Size: ${result.fixtureSize}
  Lumens per Fixture: ${result.lumensPerFixture} lumens

SPACING & LAYOUT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Layout: ${result.spacing.layout.rows} rows × ${result.spacing.layout.columns} columns
  Distance from Wall: ${result.spacing.fromWall} ${result.spacing.unit}
  Row Spacing: ${result.spacing.layout.rowSpacing} ${result.spacing.unit}
  Column Spacing: ${result.spacing.layout.columnSpacing} ${result.spacing.unit}

RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${result.recommendations.map((rec, i) => `  ${i + 1}. ${rec}`).join('\n')}

SHOPPING LIST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PRIMARY FIXTURES:
  □ ${result.numberOfFixtures}× ${result.fixtureSize} LED Recessed Lights
    • Minimum ${result.lumensPerFixture} lumens per fixture
    • Total lumens: ${result.totalLumensNeeded.toLocaleString()}
    • Recommended: 3000K color temperature (warm white)
    • Dimmable preferred
    • IC-rated if near insulation

INSTALLATION HARDWARE:
  □ ${result.numberOfFixtures}× Junction boxes (if not included)
  □ ${result.numberOfFixtures * 2}× Wire connectors
  □ Electrical wire (14/2 or 12/2 gauge)

CONTROLS (OPTIONAL):
  □ 1× Dimmer switch (LED compatible)
  □ 1× Switch plate/cover

TOOLS NEEDED:
  □ Hole saw (${result.fixtureSize})
  □ Stud finder
  □ Fish tape
  □ Voltage tester
  □ Wire strippers and cutters
  □ Drill and driver bits

ESTIMATED COST (${market.code}):
  Fixtures: ${format(result.numberOfFixtures * market.fixturePriceLow)} - ${format(result.numberOfFixtures * market.fixturePriceHigh)}
  Hardware: ${format(market.hardwareLow)} - ${format(market.hardwareHigh)}
  Total: ${format(result.numberOfFixtures * market.fixturePriceLow + market.hardwareLow)} - ${format(result.numberOfFixtures * market.fixturePriceHigh + market.hardwareHigh)}

INSTALLATION NOTES:
  • Space fixtures ${result.spacing.betweenFixtures} ${result.spacing.unit} apart
  • Keep first fixtures ${result.spacing.fromWall} ${result.spacing.unit} from walls
  • Arrange in ${result.spacing.layout.rows} rows × ${result.spacing.layout.columns} columns
  • Always turn off power at breaker before working
  • Check local electrical codes and permits
  • Consider hiring a licensed electrician

═══════════════════════════════════════════════════════════
Generated by Pen Lighting Calculator by Pen Homes
Professional Lighting Design
═══════════════════════════════════════════════════════════
`;

    // Create a blob and download
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pen-lighting-${roomType}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Button onClick={handleExport} variant="outline" className="gap-2">
      <FileDown className="h-4 w-4" />
      Export Report
    </Button>
  );
}
